
management:
  server:
    port: 9999
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,info,metrics,prometheus,quartz
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

spring:
  application:
    name: kafka-service

kafka-service:
  kafka:
    consumer:
      consumer-concurrency: ${KAFKA_CONSUMER_CONCURRENCY:1}
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: ${KAFKA_GROUP_ID}
      topics: ${KAFKA_TOPICS}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET}
      session-timeout-ms: ${KAFKA_SESSION_TIMEOUT_MS}
server:
  port: 8081
